# Generated by Django 4.1.5 on 2023-01-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50, verbose_name='Название урока')),
                ('lesson_desc', models.TextField(verbose_name='Описание урока')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.FileField(upload_to='uploads/{Lesson.pk}', verbose_name='Изображение')),
            ],
        ),
    ]
